version: "3"

services:
  backend:
    image: nandinibhawsar/shopkart:backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/ecommerce

  frontend:
    image: nandinibhawsar/shopkart:frontend
    ports:
      - "3000:3000"        
    depends_on:
      - backend           